# redis 配置
spring:
  redis:
    host: 192.168.100.33
    port: 6379
    password: safedog@2017
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
